name: wallet
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_fuels: 0.0.16
  flutter_fuelet_contracts: 0.0.9+1
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.16
  flutter_bloc: ^8.1.1
  freezed: ^2.3.2
  freezed_annotation: ^2.1.0
  flutter_secure_storage: ^7.0.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  rxdart: ^0.27.7
  dio: ^5.0.1
  overlay_support: ^2.1.0
  url_launcher: ^6.1.9
  webview_flutter: ^4.0.5
  mobile_scanner: ^2.1.0
  graphql: ^5.1.3
  json_annotation: ^4.8.0
  qr_flutter: ^4.0.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter:
  assets:
    - assets/icons/
    - assets/icons/arrows/
    - assets/images/
